AllCops:
  Exclude:
    - '/**/db/**/*.rb'

Style/Encoding:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/AndOr:
  Enabled: false

Metrics/LineLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Style/GlobalVars:
  Enabled: false

Style/SignalException:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/RegexpLiteral:
  Enabled: false

Style/BracesAroundHashParameters:
  Enabled: false

Style/SingleSpaceBeforeFirstArg:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Style/FormatString:
  Enabled: false

Style/FileName:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

AlignParameters:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false
